apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: {{ .Values.reponame }}:{{ .Values.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: I just deployed my first tag on Kubernetes!
